### ISSUE TITLE
Needs a screenshot

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.openmw.OpenMW#1]
This app needs one or more screenshots added to the appdata, otherwise it looks a bit rubbish in software stores.

https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.NAaRfc0FRyV9L_chVuKe8gHaEK%26pid%3D15.1&f=1

https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.gamingonlinux.com%2Fuploads%2Farticles%2Ftagline_images%2F857138787id4743gol.jpg&f=1

https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.KypxTjh0dL-d4NpYmWX1AwHaEK%26pid%3D15.1&f=1

https://proxy.duckduckgo.com/iu/?u=http%3A%2F%2Fosworld.pl%2Fwp-content%2Fuploads%2FOpenMW-Bloodmoon-kraina.jpg&f=1

https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.0DDffoZmBKgb3dTdQJblmAHaD0%26pid%3D15.1&f=1

**Comment by LeandroStanger** [comment]
@nedrichards could help

**Comment by ananace** [comment]
There are screenshots available, they're apparently just not in the appdata.

I'll have a look at this after FOSDEM

**Comment by ananace** [comment]
Had another look at this - after forgetting about it completely, sorry.

There are screenshots in the appdata, to quote the AppData from 0.43.0:
```xml
...
 <screenshots>
  <screenshot type="default">
   <image>http://wiki.openmw.org/images/b/b2/Openmw_0.11.1_launcher_1.png</image>
   <caption>The OpenMW launcher</caption>
  </screenshot>
  <screenshot>
   <image>http://wiki.openmw.org/images/f/f1/Screenshot_mournhold_plaza_0.35.png</image>
   <caption>The Mournhold's plaza on OpenMW</caption>
  </screenshot>
  <screenshot>
   <image>http://wiki.openmw.org/images/5/5b/Screenshot_Vivec_seen_from_Ebonheart_0.35.png</image>
   <caption>Vivec seen from Ebonheart on OpenMW</caption>
  </screenshot>
 </screenshots>
...
```

So if there aren't screenshots appearing in the software stores, then something else is broken.

**Comment by LeandroStanger** [comment]
![captura de tela de 2018-04-22 08-31-04](https://user-images.githubusercontent.com/26097419/39094542-84a31fe0-4607-11e8-9ce0-1ede0db50e97.png)

**Comment by ananace** [comment]
That is very strange indeed, I can even find the images in question cached and mirrored on flathub.org - as part of the automated packaging, so something is definitely broken somewhere.

https://flathub.org/repo/screenshots/org.openmw.OpenMW-stable/1248x702/org.openmw.OpenMW-ca8dea749dfc91defd3023fca8c0c164.png

**Comment by ananace** [comment]
The screenshots are now rendering on flathub.org

Might've been because of a faulty id in the appdata xml, could you have another test to see if it's solved for you as well?

**Comment by LeandroStanger** [comment]
![captura de tela de 2018-04-23 12-16-42](https://user-images.githubusercontent.com/26097419/39135863-525ea754-46f0-11e8-9049-e80417f9c018.png)
