### ISSUE TITLE
openmw-essimporter not included 

### ISSUE THREAD

**Issue by Gavus** [flathub/org.openmw.OpenMW#10]
Hi!

I wanted to convert an old morrowind save to openmw format, and needed openmw-essimporter. I couldn't find it in the flatpak. Is it possible to include it in the future?

**Comment by ananace** [comment]
The ess importer is a command-line utility, so it doesn't have any desktop icon or other such launcher.
You can still launch it from the Flatpak, you just need to use `flatpak run --command=openmw-essimporter org.openmw.OpenMW` to do so.
