### ISSUE TITLE
Obsolete runtime?

### ISSUE THREAD

**Issue by terzag** [flathub/org.openmw.OpenMW#12]
Hello,
When installing the package from Flathub, I get the following:
```
Required runtime for org.openmw.OpenMW/x86_64/stable (runtime/org.kde.Platform/x86_64/5.14) found in remote flathub
Do you want to install it? [Y/n]: 
Info: org.freedesktop.Platform.GL.default//19.08 is end-of-life, with reason:
   The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
```
The runtime might need to be updated if possible.

**Comment by ananace** [comment]
Seems like the KDE and Freedesktop platforms have a slightly different release cadence, since KDE's 5.14 platform is still supported even though it depends on an EOL Freedesktop platform.  
I'll see about moving OpenMW to the latest 5.15 instead.

**Comment by ananace** [comment]
And this will have to wait until the upcoming 0.47.0 release for necessary code fixes to work with the more modern compilers.
