### ISSUE TITLE
Use OpenMW/osg instead of openscenegraph/OpenSceneGraph

### ISSUE THREAD

**Issue by Torbuntu** [flathub/org.openmw.OpenMW#14]
The build instructions for [OpenMW](https://gitlab.com/OpenMW/openmw/-/wikis/development/development_environment_setup#openscenegraph) say
```
OpenSceneGraph
It is recommended to use the OpenMW/osg fork of OpenSceneGraph. 
OpenMW still works with "vanilla" OpenSceneGraph, but may run at slightly lower frame rate.
```

Is there a reason this build isn't using that instead?
```
url: https://github.com/OpenMW/osg/archive/refs/tags/OpenSceneGraph-3.6.5.tar.gz
sha256: 0bc42b60584a8b3bafdec65d401dad3fbca4b398cd715550647608c3d9343f43
```
Using runtime-version 5.15, boost from https://boostorg.jfrog.io/artifactory/main/release/1.72.0/source/boost_1_72_0.tar.gz, and the OpwnMW/osg I got this to build and run locally in flatpak really well.

**Comment by ananace** [comment]
The upcoming 0.47.0 release - currently in the beta branch - is switching to it along with a more modern runtime.  
The current 0.46 code isn't guaranteed to work perfectly with the forked OSG, hence why it's been staying on an official build here

**Comment by ananace** [comment]
And now that 0.47.0 is released, the Flatpak has moved to the OpenMW fork of OSG.
