### ISSUE TITLE
OpenMW flatpak has no sound on F35

### ISSUE THREAD

**Issue by Zlopez** [flathub/org.openmw.OpenMW#16]
Hi,

I'm using Fedora 35 Silverblue and don't have any sound in OpenMW.

I originally reported the [issue under LuxTorpeda](https://github.com/luxtorpeda-dev/luxtorpeda/issues/107) running in Steam Flatpak, but found out that when using the OpenMW flatpak directly I have the same issue.

**Comment by ananace** [comment]
And now with 0.47.0 this should be fixed - as soon as the build finishes and the new release appears on Flathub.
