### ISSUE TITLE
bsatool not present in Flathub version of OpenMW

### ISSUE THREAD

**Issue by glasssaab** [flathub/org.openmw.OpenMW#17]
bsatool doesn't seem to be present in Flathub version of OpenMW - certain mods installed using PortMod fail as it can't find it.
Also added on [https://gitlab.com/OpenMW/openmw/-/issues/6840](https://gitlab.com/OpenMW/openmw/-/issues/6840).

**Comment by psi29a** [comment]
Won't flipping the no to a yes work here?
https://github.com/flathub/org.openmw.OpenMW/blob/master/org.openmw.OpenMW.yaml#L166

**Comment by ananace** [comment]
I can enable it as soon as I'm off work, wasn't anything that used it when the Flatpak was created

**Comment by glasssaab** [comment]
Thanks anance - I notice build failed - looks like it couldn't find some screenshots it's looking for.

builddir/files/share/appdata/org.openmw.OpenMW.appdata.xml: FAILED:
• url-not-found         : <screenshot> failed to download (HTTP 404: Not Found) [https://old-wiki.openmw.org/images/b/b2/Openmw_0.11.1_launcher_1.png]
• url-not-found         : <screenshot> failed to download (HTTP 404: Not Found) [http://old-wiki.openmw.org/images/a/a3/0.40_Screenshot-Balmora_3.png]
• url-not-found         : <screenshot> failed to download (HTTP 404: Not Found) [https://old-wiki.openmw.org/images/f/f1/Screenshot_mournhold_plaza_0.35.png]
• url-not-found         : <screenshot> failed to download (HTTP 404: Not Found) [https://old-wiki.openmw.org/images/5/5b/Screenshot_Vivec_seen_from_Ebonheart_0.35.png]

**Comment by glasssaab** [comment]
https://wiki.openmw.org/images/Openmw_0.11.1_launcher_1.png
https://wiki.openmw.org/images/0.40_Screenshot-Balmora_3.png
https://wiki.openmw.org/images/Screenshot_mournhold_plaza_0.35.png
https://wiki.openmw.org/images/Screenshot_Vivec_seen_from_Ebonheart_0.35.png

**Comment by ananace** [comment]
Yep, those URLs have been changed a few times during the wiki migration. Guess I'll have to modify the original appstream XML again to keep a stable build on Flathub.

**Comment by hfiguiere** [comment]
you can also patch here.

**Comment by glasssaab** [comment]
Thanks guys.
