### ISSUE TITLE
Update runtime to 19.08

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.openmw.OpenMW#7]

**Comment by ananace** [comment]
I have a local branch with that change, but I haven't pushed it as Qt 4 is starting to require a tiresome amount of patching just to keep it compiling under the newer platform versions.

I was thinking of moving the project onto the org.kde.Platform runtime instead, to switch to Qt 5, and I just pushed the branches where I was experimenting with this. I just need to look over the other dependency upgrades as well, as something's crashing in OpenCS when 3D rendering.

**Comment by ananace** [comment]
Well, I was able to replicate the same crash in the current stable release as well, so it's something that has to be fixed - but it's not a regression in switching away from the old platform and dependencies.
